server {
    listen 10042;
    server_name embedding.localhost;

    root /var/www/static/embedding;
    index index.html;

    location /favicons/ {
        alias /var/www/static/favicons/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
