server {
    listen 8080;
    server_name tracker.my-product.com;

    resolver 1.1.1.1;
    resolver_timeout 5s;

    location /proxy-test/ {
        # curl -H "Host: tracker.my-product.com" http://localhost:8080/proxy-test/style.css

        set $target_host $host;
        if ($host ~* ^tracker\.(.+)) {
            set $target_host www.$1;
        }

        #proxy_pass http://$target_host:8080$request_uri;
        proxy_pass http://127.0.0.1:8080$request_uri;
        proxy_set_header Host $target_host;
        proxy_ssl_server_name on;
    }

    location /ui/.host/asset-redirects/ {
        # curl -H "Host: tracker.my-product.com" http://localhost:8080/ui/.host/asset-redirects/global-navigation

        set $target_host $host;
        if ($host ~* ^tracker\.(.+)) {
            set $target_host www.$1;
        }

        #proxy_pass http://$target_host:8080$request_uri;
        proxy_pass https://qa.nshiftportal.dev/ui/.host/asset-redirects/;
        proxy_set_header Host $target_host;
        proxy_ssl_server_name on;

        # Fix for large headers
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;

        # Strip the "Content-Security-Policy" header
        proxy_hide_header Content-Security-Policy;
    }
}
