server {
    listen 10042;
    server_name www.localhost;

    location /favicon.ico {
        alias /var/www/static/favicon.ico;
    }

    location /favicons/ {
        alias /var/www/static/favicons/;
    }

    location /proxy-test/ {
        # curl -H "Host: www.localhost" http://localhost:10042/proxy-test/style.css

        #root /var/www/static;
        alias /var/www/static/;
    }
}
