server {
    listen 8080;
    server_name www.my-product.com;

    location /proxy-test/ {
        # curl -H "Host: www.my-product.com" http://localhost:8080/proxy-test/style.css

        #root /var/www/static;
        alias /var/www/static/;
    }
}
