worker_processes 1;

error_log /dev/stderr info;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log /dev/stdout;
    sendfile        on;

    include /etc/nginx/sites/*.conf;
}
